# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: "test"

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json

-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
        args: ["core"]

-   repo: https://github.com/pyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: ["core"]

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.931
#     hooks:
#     -   id: mypy

-   repo: https://github.com/pyCQA/bandit
    rev: 1.7.2
    hooks:
    -   id: bandit
        args: ["-r","core"]